### PR TITLE
Image setup

### PR DESCRIPTION
**Pull request by poquirion**
Here is a Dockerfile, an a travis process that build image and push it on dockerhub.

We have tested the image on the INSPQ data and all seem good. 
I still miss the readme about how to setup the docker push to the right repo. Right now the image is lives on the c3g dockerhub page (https://hub.docker.com/repository/docker/c3genomics/ncov-tools). It can stay there, but then @jts needs a travis setup, since the jts account is not an organization one I think it is impossible for me to have to right to trigger a travis build form it.

### CODE REVIEW

**Comment by jts** [comment]
Thanks @poquirion!

**Comment by poquirion** [comment]
ohhh, that is where things are happening, I should probably setup things from there.
https://github.com/CanCOGeN-V/ncov-tools

**Comment by jts** [comment]
No, this is the "official" repo (if you can call it that), the other is just a mirror. Sorry for not merging this PR yet I am side tracked with other things right now.

Jared

**Comment by rdeborja** [comment]
Created a new merge branch (remove_ncov_parser_add_po_pr) which includes your PR and adds the removal of the parser package (set as a seperate repo simpsonlab/ncov-parser) and updates the environment to install the parser package from pypi.  This PR will be submitted as part of that branch.

**Comment by jts** [comment]
Thanks @poquirion and @rdeborja

**Pull request merged**
